M48
; DRILL file {KiCad 9.0.0} date 2025-06-11T08:44:55+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-11T08:44:55+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X116.32Y-151.36
X116.32Y-157.14
T2
X57.645Y-100.0
X113.255Y-100.0
M30
