M48
; DRILL file {KiCad 9.0.0} date 2025-06-04T09:40:23+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-04T09:40:23+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X95.32Y-62.11
X95.32Y-67.89
T2
X32.645Y-94.0
X88.255Y-94.0
M30
